language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.2.0.0
env:
  - RSPEC_VERSION=2.14
  - RSPEC_VERSION=2.99
  - RSPEC_VERSION=3.0
  - RSPEC_VERSION=3.8
  - RSPEC_VERSION=master
sudo: false
cache: bundler
script: bundle exec rake ci
